bundle.list, hostinfo/all.lua, hostinfo/login.lua
This plugin can be used to monitor login.defs settings 
to ensure proper security practices such as password
encryption methods, login retries, etc.
=> Add hostinfo plugin to gather info from login.defs

bundle.list, hostinfo/all.lua, hostinfo/misc.lua, hostinfo/sshd.lua
This is an example for the WALDO team to simplify hostinfo development in the case of spawning a process and reading its output.
=> execFileToBuffers and sshd example

lua_modules/line-emitter/lib/emitter.lua
I profiled the Line-Emitter subsystem and found out the parsing on 30 MB of
```abcdefghijklmnopqrstuvwxyz\n``` were using 700 MB - 1000 MB of memory. The plugin architecture reads stdout and stderr from processes, and even though plugins do not usually emit 30 MB worth of data, enough plugins and enough lines of data will use a significant amount of RAM. This PR optimizes the line splits with ```gmatch``` so it get's jitted, parsed within C, and does not use unnecessary memory copies. The same test on 30 MB of the alphabet with this PR resulted in memory usage of 30 MB.
=> line emitter optimizations

check/base.lua
common practice is to bulk create checks (via ansible or other automation software). If many agent.plugin checks are created in a short period of time, then there is basically a fork bomb of processes running on an ansible deploy. This tweak deferrers the plugins running until after all of them are setup and the period has expired.
=> wait for expiration of timer to run the check

check/base.lua, lua_modules/line-emitter/lib/emitter.lua
All checks on the same period are getting ran at the same time... this PR 
* jitters the check period (period + [1 ms up to 15 seconds])
* optimizes the split stream implementation (less memory)
* the line-emitter pushes data to the nextTick
=> jitter the check schedule

CMakeLists.txt
This will allow us to create test builds using FORCE_BUILD env variable.
=> enabling setting a force version for test

hostinfo/autoupdates.lua, hostinfo/base.lua, hostinfo/cron.lua, hostinfo/cve.lua, hostinfo/deleted_libs.lua, hostinfo/fileperms.lua, hostinfo/fstab.lua, hostinfo/ip4routes.lua, hostinfo/ip6routes.lua, hostinfo/ip6tables.lua, hostinfo/iptables.lua, hostinfo/kernel_modules.lua, hostinfo/last_logins.lua, hostinfo/login.lua, hostinfo/packages.lua, hostinfo/pam.lua, hostinfo/passwd.lua, hostinfo/remote_services.lua, hostinfo/services.lua, hostinfo/sshd.lua, hostinfo/sysctl.lua, tests/test-hostinfo.lua
*Why*
Makes sure the agent can't crash with failing hostinfo's.
*How*
Adds a pcall around the hostinfo run functions to capture any errors
=> fix(hostinfo): add pcall around hostinfo:run()

hostinfo/README.md, hostinfo/init.lua, runners/hostinfo_runner.lua
People have been asking me questions like:
- Whats the average/max hostinfo return data size?
- Whats the average/overall run time for the hostinfos?
These two should help me more accurately answer those questions instead of taking a guess.
Should also help us optimize scheduling for data gathering i.e. run the super slow/large ones only once a day to cache and the others can be cached several times a day or per hour.
=> feat(hostinfo/debug): Added a couple of benchmarking utils for output size and run time

hostinfo/fail2ban.lua
waldos ohai plugin limits this at 500. it gets rather large considering public ip servers get bombarded with brute force attempts
=> refactor(fail2ban): rate limit the output from fail2ban to 500 entries

hostinfo/php.lua
Make this hostinfo check compatible with facebooks hhvm
Relies on [#6270](https://github.com/facebook/hhvm/pull/6270)
Closes #873
=> fix(hostinfo/php)

check/base.lua
*Why*
Some powershell versions require stdin to be closed to exit correctly.
In addition, some ruby variants crash when stdin is not closed.
Fixes custom plugins.
=> plugin: close stdin to prevent hangs on windows

agent.lua, features.lua, main.lua
*What*
Adds `monitoring_private_zone` to the config file and propagates through to the AEP via the features.
=> private_zone: add private zone configuration and feature

hostinfo/init.lua
Only populate the HOST_INFO_TYPES array with types valid on the host OS. This is sent down to ele for get types. Solves issue #583
=> fix(hostinfo/init)

hostinfo/base.lua
Prevent erronously added undefined error messeages from being added to our response
Sometimes working hostinfos that cast their errors out as objects will have a no error or data returned error in their response.
=> fix(hostinfo/base)

hostinfo/postfix.lua
Default message when postfix isnt running was a little wrong.
=> fix(hostinfo/postfix): fix typo error in default message when postfix isnt running

hostinfo/README.md, hostinfo/all.lua, hostinfo/debug/HOSTNAME.json, hostinfo/hostname.lua, static/tests/hostinfo/hostname_in.txt, static/tests/hostinfo/hostname_out.txt, tests/test-hostinfo.lua
This pr also changes the test-hostinfo file to now say whats wrong. 
i.e.
`      local errMsg = 'Not ok: outFixture and outTable dont match.\nExpected:'..outFixture..'Got:'..outTableStr
`
from
`
local errMsg = 'Not ok: outFixture and outTable dont match.
`
=> feat(hostinfo/hostname): Add a hostinfo for fetching hostname

hostinfo/fileperms.lua
format as unsigned octal instead of decimal.
Files with octal == 644 were coming back as 420.
=> fix(hostinfo/fileperms): Fix fileperms octalfileperms, 

constants.lua
Increase the maximum check period to 86400 seconds (1 day)
Update the variable in agent code (and a partner PR for the ele repository)
Create a check with a check period great than 1800 (and less than or equal to 86400).
Rackspace Metrics has a test that they want to run daily and not run on a 30 minute interval.  A test like an SSL certificate check (checking attributes like expiration) is another example of checks that shouldn't and don't need to be run on a 30 minute interval.
Needs double checking by someone familiar with the code to make sure I didn't miss any dependencies.  
Has a companion PR in the ele repo that will need to get approved.
Determine the ordering of how these should be merged and deployed (probably ele first, then agent)
Create a story with Intelligence to change …
=> Update maximum check period to 1 day instead of 30 minutes

cmake/package/systemd/service.in
Adding `RestartSec` will configure systemd to always try to restart the agent and not give up.
=> add restartsec to systemd options

docker-compose.yml
This commit fixes the following error:
```
$ docker-compose run build make clean
ERROR: The Compose file './docker-compose.yml' is invalid because:
build.environment.TRAVIS contains true, which is an invalid type, it should be a string, number, or a null
```
=> Fix docker-compose.yml syntax

CMakeLists.txt, cmake/repo/reprepro.in
The agent ultimately calls `xenstore-read name` which comes from the package xenstore-utils. That package apparently used to get pulled in by xe-guest-utiltiies, which is pre-installed on the Ubuntu distribution.
=> Declare xenstore utils dependency

CHANGELOG, package.lua
Includes https://github.com/virgo-agent-toolkit/virgo-base-agent/pull/192
This pulls in the following commits to try and resolve an issue with proxy connections staying in a CLOSE_WAIT state.
https://github.com/luvit/luvit/pull/1031
https://github.com/luvit/luvit/pull/1032
=> Bump to 2.6.18

Make.bat
For Windows the `Make.bat` is used to simulate make on Linux. As a side effect, it's not as robust at using the versions declared in the wrapper build script -- in fact, it seems to pretty much ignore them. Worse still, the `get-lit` powershell script used in `make.bat` was always downloading the latest from master instead the version set at the top of `make.bat`. 
A mismatch in lit version would result in errors like this when running the agent:
```
...s64/home/Administrator/luvi-sigar/src/lua/luvibundle.lua:321: bundle:deps/require.lua: cannot load incompatible bytecode
```
=> Use LIT_VERSION in Windows build's make.bat

CHANGELOG, check/base.lua, check/mysql.lua, package.lua
https://jira.rax.io/browse/CMC-2271
- Include rev 21 for the mysql client library lookup
- Fix an issue where the stderr logging of sub-process checks (such as mysql) was not including the actual chunk
- Bump the luvi version to include latest openssl which resolves compatibility with MySQL 8 client library
After a test build I'll set the version to a non-beta `2.6.22`
=> Include lookup of mysql client library rev 21

.gitignore, Make.bat, package.lua
https://jira.rax.io/browse/CMC-2273
Even with the luvi set to 2.9.3-sigar in `package.lua` the built agent exe was producing an error like https://github.com/luvit/lit/issues/252 .
What ended up fixing this (in local build testing at least) was doing two things:
1. Build lit from source, such as what the Linux builder script does here: https://github.com/virgo-agent-toolkit/rackspace-monitoring-agent-buildbot-builder/blob/master/build.sh#L38-L44 
2. Instead of putting the lit-building logic way over in that repo, just incorporate it into this repo's `make.bat` since it was already doing "get lit" stuff
=> Build lit as part of regular Windows build

CHANGELOG, CMakeLists.txt, Makefile, package.lua
For https://jira.rax.io/browse/CMC-2295 we need to remove the explicit dependency on the xenstore-utils package so that the VM setup has the option to provide `xenstore-read` from newer packages, such as `xe-guest-utilities`.
=> Removed explicit DEB dependency on xenstore-utils package

check/windows/winbase.lua
We came to an issue where we are not aware what the issue is because of missing log statements and also table type is not converted to string before concatenation which is breaking the execution. So we added a new function which is returning string value from table type object.
=> Table to string changes

CHANGELOG, Make.bat, package.lua
We got a query from customer that windows perf_os check are not working. We identified later that it is with all windows checks and it is because of some LIT version update and also related with windows TLS. So we rolled back to a latest version combination on which these checks are working fine.
=> updated LUVi and LIT version for windows check issue

CHANGELOG, package.lua
Moving back to 2.6.23 because we realized we can't push out only the Windows binaries. All the install files have to be here, so we copied the 2.6.24 Windows installers back to the 2.6.23 cloudfiles bucket and will push that out.
Another PR on same note -> https://github.com/rax-maas/ele-agent-repo-distribution/pull/38
=> Rolled back version to 2.6.23

check/base.lua, static/tests/custom_plugins/timeout.sh
All relevant findings regarding the killing of spawned children and limitations of the libuv framework to do so were added to the code, and timeout.sh timeout was reduced to 5 seconds so that other tests are not stalled for so long.
=> Adding notes for plugin timeout

CONTRIBUTING.md, check/base.lua
If we pass SPAWN_CHECKS_DETACHED as true while running tests, we will be able to spawn child checks as detached processes, which can then be killed within the specified timeout. This will help in testing whether spawning detached child processes in staging will have any repercussions
=> Using an env variable as a flag to spawn detached child checks

package.lua
The luvi sigar version 2.9.4 doesn't exist, 2.7.6-2 is the correct version for Darwin
=> Fix Luvi Sigar version
