virgo-agent-toolkit/rackspace-monitoring-agent

- check/network.lua
This adds a new metric 'link_state' that can take one of three values:
- 'up' when the interface driver reports that the link is operational,
- 'down' when the interface driver reports that no link is detected,
- 'unknown' if either the interface has been shut down, or the kernel is unable to get interface status information from the driver.
```javascript
"metrics": [
"link_state": {
"t":"string",
"v":"up",
"u":"link_state"
},
[...]
]
```
It is linux-only so far because of my lack of windows skills.
> feat(check/network): add interface link state on linux

- setup.lua
Relates to: https://github.com/virgo-agent-toolkit/rackspace-monitoring-agent/issues/643
I'd done this in December but wasn't able to try it out myself.  Managed now and all works as expected.
> Improve prompt regarding entity creation - #643

- .luacheckrc
- check/base.lua
- check/plugin.lua
* Remove the stdout and stderr cache
* Print anything from stderr to the log directly
* Lint
* Add .luacheckrc
> fix(plugin): don't cache stdout and stderr

- .luacheckrc
- main.lua
- runners/check.lua
- runners/hostinfo.lua
- runners/tests.lua
- tests/test-agent.lua
> fix(hostinfo): hostinfo and check runners work

- bundle.list
- hostinfo/all.lua
- hostinfo/packages.lua
Current only supports Debian/Ubuntu and Cent/RHEL.
> Add hostinfo plugin to list installed packages

- lib/agent.lua
> trim token and id

- cmake/WinUpload.cmake
rclone cannot copy one file to a different remote name
> Create a local copy of the legacy MSI, then upload

- main.lua
looks like the following:
```
1.9.11 (luvi v2.1.1, libuv 1.6.0, OpenSSL 1.0.2b 11 Jun 2015)
```
> change version string

- Make.bat
- Makefile
> Fix(Makefile): Fix error due to trying to find the compiled agent inside build/build instead of just build

- hostinfo/packages.lua
This check was broken, need to initialize sigar context with :new, cant just req(sigar).ctx
> Fix(hostinfo/packages)

- hostinfo/all.lua
- hostinfo/pam.lua
Hostinfo plugin to retrieve data from pluggable auth module definitions, slightly more reliable than the ohai variant
> feat(hostinfo/pam)

- hostinfo/all.lua
- hostinfo/fileperms.lua
Added a hostinfo check to retrieve file permissions on linux
> feat(hostinfo/fileperms)

- hostinfo/all.lua
- hostinfo/passwd.lua
> feat(hostinfo/passwd): Added a hostinfo check to get passwd stati

- hostinfo/all.lua
- hostinfo/cve.lua
Added a check to parse and find cve fixes in changelogs on rpm & debian based distros. ported from ohai-plugins/vulnerabilities
> feat(hostinfo/cve)

- Make.bat
- Makefile
- check/plugin.lua
- package.lua
> fix(plugin): fix type for new luvit

- check/init.lua
- check/raxxen.lua
```
metric ovs_datapath.flow_count uint64 25
metric ovs_datapath.hit uint64 205189782
metric ovs_datapath.missed uint64 40026584
metric ovs_cpu double 0
metric ovs_datapath_masks.total uint64 11
metric ovs_datapath_masks.hit uint64 1614383088
metric ovs_datapath_masks.hit_per_pkt uint64 6.58
metric instance_count uint64 9
metric ovs_datapath.lost uint64 0
```
> add initial raxxen check

- .travis.yml
- Makefile
- check/raxxen.lua
Adds support to Travis for running luacheck automatically.
> R4R: add luacheck

- agent.lua
- features.lua
- main.lua
- tests/test-agent.lua
```
monitoring_health disabled
```
* Adds a features.lua module
* Adds tests
> add feature flag for health

- hostinfo/all.lua
- hostinfo/apache2.lua
- static/tests/hostinfo/apache2_VhostConfig_in.txt
- static/tests/hostinfo/apache2_VhostConfig_out.txt
- static/tests/hostinfo/apache2_VhostOutput_in.txt
- static/tests/hostinfo/apache2_VhostOutput_out.txt
- static/tests/hostinfo/apache2_apacheOut_in.txt
- static/tests/hostinfo/apache2_apacheOut_out.txt
- tests/test-hostinfo.lua
Port waldos apache2. This feature is currently a WIP
> feat(hostinfo/apache2):

- tests/test-hostinfo.lua
Use a template function for the tests to reduce code
> refactor(test-hostinfo)

- hostinfo/all.lua
- hostinfo/fail2ban.lua
- static/tests/hostinfo/fail2ban_activitylog_in.txt
- static/tests/hostinfo/fail2ban_activitylog_out.txt
- static/tests/hostinfo/fail2ban_bannedstats_in.txt
- static/tests/hostinfo/fail2ban_bannedstats_out.txt
- static/tests/hostinfo/fail2ban_jailslist_in.txt
- static/tests/hostinfo/fail2ban_jailslist_out.txt
- static/tests/hostinfo/fail2ban_logfilepath_in.txt
- static/tests/hostinfo/fail2ban_logfilepath_out.txt
- tests/test-hostinfo.lua
Port ohai check reqd by waldo. Checks the status and things of the fail2ban app
Tests are dependent on #850 and are incoming, with a rebase.
> feat(fail2ban)

- hostinfo/debug/NGINX_CONFIG.json
- hostinfo/nginx_config.lua
Properly assign docroots, domains and listen, accounting for the fact that domain doesnt need to be assigned before either of the others in the conf files
> fix(hostinfo/nginx)

- hostinfo/README.md
- hostinfo/all.lua
- hostinfo/debug/PHP.json
- hostinfo/php.lua
- static/tests/hostinfo/php_ApacheError_in.txt
- static/tests/hostinfo/php_ApacheError_out.txt
- static/tests/hostinfo/php_Modules_in.txt
- static/tests/hostinfo/php_Modules_out.txt
- static/tests/hostinfo/php_VersionAndError_in.txt
- static/tests/hostinfo/php_VersionAndError_out.txt
- tests/test-hostinfo.lua
Port of the ohai plugins php_web check
> feat(hostinfo/php)

- hostinfo/nginx_config.lua
Add location info to vhosts and refactor getVhosts
Also removed the hard requirement for a domain or <server_name> directive since nginx can be configured without one.
> fix(nginx)

- hostinfo/magento.lua
- hostinfo/wordpress.lua
Prevent errors trying to call asyncforeachlimit on empty lists
> fix(hostinfo/wordpress&magento)

- README.md
Minor readme changes, place waffle graph above build status buttons, and add pre-reqs for linux distros
> refactor(readme)

- main.lua
- package.lua
- setup.lua
> add -N no entity create support

- hostinfo/debug/LSYNCD.json
- hostinfo/lsyncd.lua
Typo fix and add functionality to check if lsyncd is installed and fix on ubuntu
> fix(lsyncd): Fix typo, bin path, add check if installed func

- hostinfo/all.lua
- hostinfo/debug/LSHW.json
- hostinfo/lshw.lua
https://jira.rax.io/secure/RapidBoard.jspa?rapidView=559&view=detail&selectedIssue=INT-1603
> Add new lshw hostinfo check

- appveyor.yml
SQL 2008 is eol and server isn't available to test against.
> Remove SQL 2008 Server Test

- check/network.lua
> add a nil check within the network check

- CHANGELOG
- package.lua
Releasing new agent to be build with new version of wix.
> Bump agent to 2.6.15

- CHANGELOG
- package.lua
Contains https://github.com/virgo-agent-toolkit/virgo-base-agent/pull/193
> Bump to 2.6.19

- CHANGELOG
- main.lua
- package.lua
This provides an option on startup to provide a command line option to provide a path to the certificate that the user wants to use.
> Allow customers to provide their own certificate

- check/mysql.lua
> More descriptive error for mysql agent failure

- CONTRIBUTING.md
- README.md
Update some wiki links in README file and also added Develop contibuting guide.
> added Developer Guide for Monitoring Agent

- CONTRIBUTING.md
Added steps to the guide for running Individual tests
> Update Contributing guide for Individual tests
